### ISSUE TITLE
Unavailable teleportation request - Achievement Cape

### ISSUE THREAD

**Issue by smolz13** [Skretzo/shortest-path#100]
Plugin thinks too highly of me, definitely don't have an achievement cape just yet.

![Screenshot 2024-10-03 211230](https://github.com/user-attachments/assets/0585b5b5-73d1-4820-b784-d59aa8a9c549)

**Comment by Skretzo** [comment]
This is hopefully fixed in version 1.15.3, and will be live in the client after review in a few days or 1 to 2 weeks.

**Comment by smolz13** [comment]
ty for all the hard work!
