### ISSUE TITLE
Meiyerditch route from Mine to ToB goes through a locked door with no way to unlock

### ISSUE THREAD

**Issue by Luunae** [Skretzo/shortest-path#107]
After being teleported to the [Meiyerditch mine](https://oldschool.runescape.wiki/w/Meiyerditch_mine) and following the no-teleportation Shortest Path to [Theatre of Blood](https://oldschool.runescape.wiki/w/Theatre_of_Blood), you are led to a door you can't pass through.

The door is between the following two tile locations (source: the "World Location" plugin):
x: 3614, y: 3205, z: 0
x: 3614, y: 3205, z: 0

Screenshot attached:
![Shortest_Path_Meiyerditch_20241015](https://github.com/user-attachments/assets/5c2633c1-628a-4e82-a43f-1b4083de4ba2)

~~Of interesting note: this door, and similarly-locked doors in the area, seem to have the following examine text: "Blocking the path."
Meanwhile unlocked doors nearby have the examine text: "A crude-looking door fashioned from random bits of wood."~~

~~Hopefully that examine text can be useful for not having to manually figure out which doors are passable. :/~~

Edit: found a door with the "Blocking the path." examine text that can be opened (between (x: 3624, y: 3222, z:0) and (x: 3624, y: 3221, z:0). Not a good heuristic. >.<

**Comment by Skretzo** [comment]
This should be fixed in version 1.16.1, which is now live in the client (assuming you have restarted your client to fetch the update). Could you please check if the issue is fixed for you?

**Comment by Luunae** [comment]
Oh, excellent, that route works now! I can probably actually finish the quests here now, thank you!
