### ISSUE TITLE
There's no need to go the long way from Port Phasmatys to the Ectofuntus

### ISSUE THREAD

**Issue by someperson** [Skretzo/shortest-path#109]
![Screenshot from 2024-10-24 11-23-17](https://github.com/user-attachments/assets/a9f75b20-275b-4100-b731-4afd6b7779c0)

**Comment by Skretzo** [comment]
Do you have ecto-tokens on you to use the gate?
Or maybe completed the quest?

**Comment by someperson** [comment]
At the time this was taken, I was in the middle of the quest and had ecto-tokens in my inventory. Although that shouldn't matter since going out through the gate is free (only going in costs tokens).

**Comment by Skretzo** [comment]
Looks like I forgot to add the gate at all

**Comment by Skretzo** [comment]
This was added in plugin version 1.16.4, and is already live in the client.

**Comment by someperson** [comment]
Thank you!
