### ISSUE TITLE
Can't walk through the tree behind the sawmill

### ISSUE THREAD

**Issue by IsekaiVictim** [Skretzo/shortest-path#110]
![image](https://github.com/user-attachments/assets/48eb21cb-a221-4455-8262-bb2e6b0645e3)
Yes, you can hop the wildy line and go around at that spot, but thats still going through the wilderness I think

**Comment by Skretzo** [comment]
> I wouldn't doubt it if someone told me this tree was added yesterday

You might be correct, or it could be that since the fence is actually inside the tree, it might be messing up my collision map generation.

**Comment by Skretzo** [comment]
This should be fixed in version 1.16.3, which is already live in the client.
