### ISSUE TITLE
Shortest path doesn't recognize runes inside Rune Pouch for teleport spells

### ISSUE THREAD

**Issue by glauzadis** [Skretzo/shortest-path#113]
I am trying to find the shortest path to cities, but since my runes for TP spells are inside the Rune Pouch, it doesn't recognize that I have the runes.

Taking the runes out of the pouch makes it behave as expected.

**Comment by joeywittig** [comment]
+1

**Comment by Mouneh** [comment]
I don't know if there's a way to help you to be seen, but i'm having the same problem haha. i started playing again for 3 weeks and every time that I was doing quests i was always wondering why they never made me use any teleporting spell, i googled so much to find out.. but not a single thread was appearing xD i finally found this githud and voila! The second i took my law runes out of my rune pouch is when.. the plugin "worked" so.. pls send help Mr creator!

**Comment by Skretzo** [comment]
This was added in version 1.16.5 and is already live in the client. Restart your client to fetch the update if you have not already done it in the past 24 hours.
