### ISSUE TITLE
Shortest path doesn't recognize runes inside Rune Pouch for teleport spells 

### ISSUE THREAD

**Issue by Mouneh** [Skretzo/shortest-path#114]
I am sorry for creating the same bug report, but I just want to make sure that we have more chances for the creator to see this issue :)! I didn't know it was a thing until i spent hours searing online why would the plugin never tell me to use my teleporting spells ha ha ha! 

So yeah, runes in the rune pouch are not taken into consideration, atleast for law runes~ I shall not put them inside, or try to for the future , thanks.

After trying a few things.. it also doesn't count the mystic air staff, I didn't test the other elements. Having all the runes out of the pouch and in the inventory is frustrating when doing quests xD but ay, as long as you have the runes in the inventory it works~

**Comment by Skretzo** [comment]
This was added in version 1.16.5 and is already live in the client. Restart your client to fetch the update if you have not already done it in the past 24 hours.
