### ISSUE TITLE
Not recognizing house location

### ISSUE THREAD

**Issue by kgaban** [Skretzo/shortest-path#116]
![image](https://github.com/user-attachments/assets/c4500e45-1b50-4bf6-8829-40cd0ef2f0f6)
![image](https://github.com/user-attachments/assets/24ed713d-88f8-4bcd-8261-9d7615f6035c)

House location is in Hosidius but it uses any house portal as teleport recommendation even when the house is not located there.

**Comment by Skretzo** [comment]
This should be fixed in version 1.16.6, and is already live in the client.
