### ISSUE TITLE
Plugin not considering spirit tree

### ISSUE THREAD

**Issue by mwang9876** [Skretzo/shortest-path#117]
It was working for my main but not this account. In my main I unlocked spirit tree, gnome slider and fairy ring, but on this account I only have spirit tree. Maybe this is the issue? 

on current account:
![image](https://github.com/user-attachments/assets/0aa0d235-1926-4e51-9a36-22e51fff5e87)

on my main:
![image](https://github.com/user-attachments/assets/a49389ad-4b34-4cbc-b2d6-9944e2c55c19)

**Comment by Skretzo** [comment]
Have you completed both Tree Gnome Village quest and The Grand Tree quest? Tree Gnome Village quest gives access to spirit trees, but The Grand Tree quest is required to travel from or to the spirit tree in the Tree Gnome Stronghold.

**Comment by mwang9876** [comment]
I see! The plugin worked fine after I finished the grand tree yesterday.

I dont know if worth to fix: the grand tree only unlocks the *from* trip
from spirit tree, all the *to* trip worked even before the quest. Also
before the grand tree quest, when I want to travel from the ardougne cape
teleport to GE, the plugin wont show the option to use spirit tree, but
that path is unlocked by gnome stronghold quest.

**Comment by Skretzo** [comment]
> the grand tree only unlocks the *from* trip from spirit tree, all the *to* trip worked even before the quest

Interesting. I have changed the plugin to work like you describe.

> Also before the grand tree quest, when I want to travel from the ardougne cape teleport to GE, the plugin wont show the option to use spirit tree, but that path is unlocked by gnome stronghold quest.

The plugin was incorrectly assuming that The Grand Tree quest had to be completed to use spirit trees. This should be fixed now to only require Tree Gnome Village quest.

All the fixes should be live in the client already in version 1.16.6.
