### ISSUE TITLE
Possible to add league clue compass as a teleport option?

### ISSUE THREAD

**Issue by adamk33n3r** [Skretzo/shortest-path#122]
You would probably have to include options for the user to select what regions they have unlocked. But this would be SO invaluable!

**Comment by Skretzo** [comment]
#123 is adding the league clue compass teleports, but is currently missing automatically determining region unlocks.

**Comment by joranvar** [comment]
It looks like the changes have been accepted, and shortest-path version 1.16.7 is now available from the RuneLite plugin hub.

**Comment by adamk33n3r** [comment]
yayyyyyy
