### ISSUE TITLE
Unable to see path on minimap only.

### ISSUE THREAD

**Issue by tom239955** [Skretzo/shortest-path#13]
Not sure the issue, maybe an update, but unable to see the path. Also when my distance is set to 0 to recalculate (to remove tiles as they are traveled) it does not always happen,

**Comment by robrichardson13** [comment]
Also getting this bug. The minimap path won't show, but if I hold CTRL and move the minimap it then appears.

**Comment by Skretzo** [comment]
I have added a [fix](https://github.com/Skretzo/shortest-path/commit/ae3a46084286047fa3e0a2eb2cfa29b3130b15cf) for the minimap path, which should be live in the client in a week or so when it has been reviewed.

> Also when my distance is set to 0 to recalculate (to remove tiles as they are traveled) it does not always happen

@tom239955 Could you elaborate on this? Can you reproduce this? A video or image would be helpful.

**Comment by Skretzo** [comment]
Feel free to re-open or make a new issue if you can consistently reproduce the path not recalculating with the distance set to 0.
