### ISSUE TITLE
Add use of Fairy Rings as an option

### ISSUE THREAD

**Issue by Oliver-Saer** [Skretzo/shortest-path#14]
Any possibility that you may be able to select Fairy Rings as an option for calculating the route?  Just as you can currently with agility shortcuts & grapple points?

**Comment by Skretzo** [comment]
This was added in [version 1.9.1](https://github.com/Skretzo/shortest-path/commit/108cdcddeca37665b03f33b7ac11b75087b225bd#diff-9b06370f3117af5108b2a6aed9d6abd9ab8557fb19f0c8e2d96cd77dfd153121) and is now live in the client.

**Comment by Oliver-Saer** [comment]
Nice work, thank you! 🤩

**Comment by Skretzo** [comment]
No problem. This update was 13 days in review (because of the Raids 3 release), but eventually it was accepted. Please let me know if you find any problems.
