### ISSUE TITLE
suggestion: option in display styles. show remaining only on the 1st tile

### ISSUE THREAD

**Issue by LukasOfLockless** [Skretzo/shortest-path#17]
would be cool to have an extra option.
showing remaining walk distance on every tile is a bit too much, one is enough

**Comment by Skretzo** [comment]
An option to do this was added in [version 1.9.2](https://github.com/Skretzo/shortest-path/commit/4e75fb99542619106cc01da14bdaa5ad1c64e7fa) and is now live in the client (restart your client to fetch the update).

For your particular case you want to set the new `Tile counter step` option to a very high number, e.g. 100000. That way the remaining walk distance will only be displayed on the first tile (and travelled distance will only be displayed on the last tile).
