### ISSUE TITLE
Pathing makes pointless detours and phases through walls

### ISSUE THREAD

**Issue by lbenedetto** [Skretzo/shortest-path#18]
Keeps pathing me through walls and such. In this example, it wanted me to make an inefficient detour north, phase through the fence, and then jump over the turnstile to get back across the fence, and then head back south again. There was no reason for the path to go anywhere near this fence.
![image](https://user-images.githubusercontent.com/4466272/192844068-8f579309-2b03-4f7d-83ad-7a64a56f0003.png)

**Comment by Skretzo** [comment]
Does this still happen? I fixed this issue 6 days ago

**Comment by lbenedetto** [comment]
Ok, probably fixed then. I created this issue 9 days ago, but in the wrong fork.
