### ISSUE TITLE
Pathing to fairy ring from GE buggy.

### ISSUE THREAD

**Issue by OreoJays** [Skretzo/shortest-path#23]
For some reason when i stand next to the northern GE Clerk and when i went to set a target for kourend catacombs. it took me to the canoe spot by ge, to take down to lumby, back to the GE, then to the fairy ring.

**Comment by Skretzo** [comment]
Yes, this is a known issue. Currently, transport time is not considered (or rather assumed to be instantaneous). I need to find a good way to incorporate this.

**Comment by EKarpinsky** [comment]
@Skretzo any update? I'd love to make a PR with data of transportation times (canoe for example is extremely long)

**Comment by Skretzo** [comment]
@EKarpinsky If you want to help out you can add transportation travel time (in ticks) to this sheet:
https://docs.google.com/spreadsheets/d/1ekNVQ19xljlcbUHnG9pDjv8sr7bCQfBq6-bw9EKrMTw/edit?usp=sharing
I have already added travel time for all boats, including canoes (separate sheet), so it's only agility shortcuts, doors, gates, ladders, staircases, etc that are missing. I plan to release this to the plugin in 1 or 2 weeks, but help after this is also very helpful and will just have to wait for the next release

**Comment by Skretzo** [comment]
> Currently, transport time is not considered (or rather assumed to be instantaneous).

This was fixed in [version 1.9.3](https://github.com/Skretzo/shortest-path/compare/4e75fb99542619106cc01da14bdaa5ad1c64e7fa...Skretzo:b57d79bfc2ded948195b68d645bd26024fe5d817). Some shortcuts are still missing transportation times which will be added eventually. Restart your client to fetch the update.
