### ISSUE TITLE
Collision map wrong around Giant's Foundry

### ISSUE THREAD

**Issue by jjlabont** [Skretzo/shortest-path#24]
![image](https://user-images.githubusercontent.com/25591758/202475955-82d18a83-2917-470b-838e-5505daf45c8b.png)

**Comment by Skretzo** [comment]
This was fixed in [version 1.9.3](https://github.com/Skretzo/shortest-path/compare/4e75fb99542619106cc01da14bdaa5ad1c64e7fa...Skretzo:b57d79bfc2ded948195b68d645bd26024fe5d817). Restart your client to fetch the update
