### ISSUE TITLE
Paths into Shilo Village Do Not Use Gate

### ISSUE THREAD

**Issue by ZaquMan** [Skretzo/shortest-path#25]
As we know, Shilo Village is only accessible one of three ways, walking in through the gate, riding the Brimhaven cart, or using the Gem Mine teleport of the Karamja 3 Gloves.  The pathing however does not use one of these means of entrance, instead directing you to no-clip through the wall.

![image](https://user-images.githubusercontent.com/43051103/204687942-1255eb8b-098c-42ab-a884-c721944c9faa.png)

Enabling the collision marking shows that the plugin recognizes the wall and vegetation as collision objects, as shown below, so I'm not sure why it's trying to go through the wall, unless it doesn't recognize the gate as an access point.

![image](https://user-images.githubusercontent.com/43051103/204688849-7cd4d377-bdbe-486a-bc2f-544f803dece2.png)

**Comment by Skretzo** [comment]
> I'm not sure why it's trying to go through the wall, unless it doesn't recognize the gate as an access point.

The broken cart entrance to Shilo Village was missing. This was fixed in [version 1.9.3](https://github.com/Skretzo/shortest-path/compare/4e75fb99542619106cc01da14bdaa5ad1c64e7fa...Skretzo:b57d79bfc2ded948195b68d645bd26024fe5d817). Restart the client to fetch the update.
