### ISSUE TITLE
Everything the plugin affects has a bunch of = signs above it

### ISSUE THREAD

**Issue by spazsadwadawf** [Skretzo/shortest-path#26]
like the title says the agility shortcuts, wildy line, fairy rings all have a bunch of = signs above it. Any ideas on how to fix it? 
![Screenshot 2022-12-15 161305](https://user-images.githubusercontent.com/120689349/207986648-ef302483-95cc-400f-9c6a-f8abeac68057.png)

**Comment by Skretzo** [comment]
Having the plugin display agility shortcuts is not really meant for the average user of the plugin, but rather for debugging when developing the plugin. You can easily disable this in the plugin settings under `Display` -> `Draw agility shortcuts`. However, if you really like having green tiles highlighting the agility shortcuts then I guess I could make this setting a little less intrusive. Alternatively you can always use the agility plugin to highlight shortcuts

**Comment by spazsadwadawf** [comment]
wait sorry skretzo I don't see the draw agility shortcuts under display in the plugin settings any ideas why?
