### ISSUE TITLE
Canoe and Boats seperate request.

### ISSUE THREAD

**Issue by Sir2Medis** [Skretzo/shortest-path#28]
Would it be possible to seperate the boat feature from canoes, i dislike the canoe system and it keeps messing with my shortest path resulting in me having to to remove boats and then readding it later.

**Comment by Skretzo** [comment]
Yes, I plan to separate `Use boats` into individual options for canoes, charter ships, passenger ships and boats.

> it keeps messing with my shortest path

If by this you mean that it creates a weird/wrong path then I would be happy if you could give me an example, but I assume this is just referring to you simply getting a path with a canoe when you don't want to use canoes.

**Comment by Skretzo** [comment]
This was added in version 1.10 and is live in the client.
