### ISSUE TITLE
Unpathing on trail to Mort'ton

### ISSUE THREAD

**Issue by DrexelR** [Skretzo/shortest-path#32]
Never snitched on a glitch before, but it's attached in the PNG. South-East corner of the trail West of Mort'ton is not traversable.

![Screenshot 2023-03-30 225934](https://user-images.githubusercontent.com/126802314/229011999-97b66d59-8643-4dfd-86a2-0f2e7ad62216.png)

<3 Thank you for making cool content for OSRS

**Comment by Skretzo** [comment]
This was fixed in version 1.10 and is live in the client.
