### ISSUE TITLE
Agility Shortcuts Broken

### ISSUE THREAD

**Issue by valarauca** [Skretzo/shortest-path#37]
Not accounting for agility short cuts

![image](https://github.com/Skretzo/shortest-path/assets/19227148/12e46e68-b98a-4901-b51b-f4577dcbe3b1)

config
![image](https://github.com/Skretzo/shortest-path/assets/19227148/c4e9b9b9-1ea6-49e5-bafa-016470e78825)

My agility level is more than sufficient for the local obstacles.

**Comment by Skretzo** [comment]
This was added in version 1.11 and is now live in the client.
