### ISSUE TITLE
Feature Request: Support all transportation methods

### ISSUE THREAD

**Issue by Intecpsp** [Skretzo/shortest-path#47]
This plugin currently supports a few transportation methods, but I'd like to request that it support all the ones currently in the game. [Here](https://oldschool.runescape.wiki/w/Optimal_quest_guide#:~:text=%2C%20Spellbook%20Swap-,Transportation,-unlocks%3A) is a good starting list from the wiki. As well as the [Ardougne cloak](https://oldschool.runescape.wiki/w/Ardougne_cloak_1#:~:text=Tower%20of%20Life-,Unlimited,-teleports%20to%20the), and the [different spellbooks](https://oldschool.runescape.wiki/w/Teleportation_spells). Obviously, there would need to be checks put in place that the player actually has access to use these (meets the requirements, similar to https://github.com/Skretzo/shortest-path/issues/4). 

I may have missed a few, but this should be a good starting point

**Comment by Intecpsp** [comment]
Adding this to the request: https://oldschool.runescape.wiki/w/Lovakengj_Minecart_Network

**Comment by Intecpsp** [comment]
Also, just found this: https://oldschool.runescape.wiki/w/Category:Transportation

**Comment by Skretzo** [comment]
Teleportation items and spells were added in version 1.13.

Minecarts were added in version 1.14.

Other transportation methods will be added at some point. Feel free to create separate issues if you want to keep track of progress on adding particular transportation methods.
