### ISSUE TITLE
Feature request: Fairy rings labels

### ISSUE THREAD

**Issue by ErlanRG** [Skretzo/shortest-path#51]
When the shortest path suggest to use a Fairy Ring, it would be pretty helpful to include a label or something that shows the  Fairy Ring destination code so you don't have to check the map for it every single time.

**Comment by Skretzo** [comment]
This is already a part of the plugin
![image](https://github.com/Skretzo/shortest-path/assets/53493631/948f3bf3-eea1-4d3c-aeb5-ce26edc1e771)

**Comment by ErlanRG** [comment]
Not sure why I don't see that. I always have to double check the map for the code. 
I will check the version and re-install if needed.

**Comment by HxxxxxS** [comment]
I was about to make a feature request issue for something similar when i saw this so i will just comment here instead.

I am seeing the fairy code on the ring as your screenshot, but i would love to be able to see the recomended fairy code more clearly when within the fairy ring UI. I find myself closing and reopening the fairy ring UI several times per play session to double check the recomended code.

**Comment by Skretzo** [comment]
In the future I want to do more highlighting of where to click, similar to the Quest Helper plugin. The fairy ring interface could be part of that too.

![image](https://github.com/Skretzo/shortest-path/assets/53493631/a774455c-20f3-4fee-9835-69ff9b393a0b)
