### ISSUE TITLE
Rotten village fence

### ISSUE THREAD

**Issue by johnathon-walnut** [Skretzo/shortest-path#52]
The plugin seems to try to path through the rotten village path as if it doesn't block the path in the tai bwo wannai area.

![image](https://github.com/Skretzo/shortest-path/assets/36936588/a4dc68f7-c5c5-4927-9152-74a0a2b50af8)

**Comment by Skretzo** [comment]
This issue was fixed in 9a9667c29fcdf437d9b2ddd1e0dde498ec7eb89c and will be part of the next plugin update.
