### ISSUE TITLE
Issue with The Stranglewood rowboat

### ISSUE THREAD

**Issue by ShaunDreclin** [Skretzo/shortest-path#53]
Looking at this path here it seems to be trying to send me to the rowboat but it's pointing to the wrong spot and the path just ends on a cliff instead

![Screenshot](https://github.com/Skretzo/shortest-path/assets/5851433/a0732b44-b461-4e99-8892-95c7cc587dcc)

**Comment by Skretzo** [comment]
This happens because I have not yet added transports for this area, e.g. boats and agility shortcuts

**Comment by Skretzo** [comment]
Fixed in 7954a180f0076ab085ca75c1b7070e910529bdd5
