### ISSUE TITLE
Shortcut ignored east to Shilo Village

### ISSUE THREAD

**Issue by Rowan-Mulder** [Skretzo/shortest-path#80]
As the title mentions, this shortcut seems to be ignored.
It does suggest the lvl 1 Log Balance up to the north, but not these lvl 30 Stepping Stones. I have 59 agility and isn't drained. I also enabled "Use agility shortcuts".
Happy to provide more information if necessary.
![image](https://github.com/Skretzo/shortest-path/assets/62886548/df609136-0c91-4b3f-aaaa-1782929deb9f)

**Comment by Skretzo** [comment]
This was added in version 1.13
