### ISSUE TITLE
Mountain Camp (Rockslide Obstacle) Not Supported 

### ISSUE THREAD

**Issue by Infinitay** [Skretzo/shortest-path#84]
![image](https://github.com/user-attachments/assets/0671e0a0-e05f-450f-b1dd-a6453b270156)

(South east tile hovered)

When trying to generate a path to the Mountain Camp, it fails to do so because I don't think it's accounting for the Rockslide obstacle you have to climb to get there

**Comment by Skretzo** [comment]
This was added in version 1.14.1 and is live in the client
