### ISSUE TITLE
Path finding seems to be broken since latest RuneScape update

### ISSUE THREAD

**Issue by xdemon9912** [Skretzo/shortest-path#93]
Yesterday, the plug-in worked perfectly, but since the "Varlamore: The Rising Darkness" patch, it is no longer working. Despite I set a target on the map, it doesn't draw the path.

RuneLite version: 1.10.38
Oldscholl revision: Rev 225
Launcher version: 2.7.2
OS Name: Microsoft Windows 11 Pro (10.0.22631 Build 22631)

**Comment by BP97XI** [comment]
same for me pal

**Comment by Skretzo** [comment]
This was fixed in plugin version 1.14.1 and will be live in the client after review, which typically takes a few days or 1 week.

**Comment by Skretzo** [comment]
The new plugin version 1.14.1 with the fix is now live in the client. Please restart your client to fetch the update.
