### ISSUE TITLE
shortest path

### ISSUE THREAD

**Issue by BP97XI** [Skretzo/shortest-path#94]
after the update shortest path does not work ive reset and and re downloaded needs to be fixed

**Comment by EarlsWorld** [comment]
I can confirm, same here.

**Comment by ama13377** [comment]
Same!

**Comment by Elvansivicus** [comment]
Same here too

**Comment by Troyoboy** [comment]
How am i going to play the game now 😢

**Comment by Skretzo** [comment]
This was fixed in plugin version 1.14.1 and will be live in the client after review, which typically takes a few days or 1 week.

**Comment by Skretzo** [comment]
The new plugin version 1.14.1 with the fix is now live in the client. Please restart your client to fetch the update.

**Comment by Nick2bad4u** [comment]
Can confirm, you can set target but no path appears.

I am on the latest version as well, 1.14.1.

[Made this gif to show you](https://[i.gyazo.com/075e8adf432a7d29376ddd840ed3991a.mp4](https://i.gyazo.com/075e8adf432a7d29376ddd840ed3991a.mp4))
