### ISSUE TITLE
Target locations doesn't account for plane

### ISSUE THREAD

**Issue by emerald000** [Skretzo/shortest-path#99]
The solver currently doesn't account for the plane of the location you pick. This also affects using a PluginMessage to specify the exact coordinate (including plane) as a target. The path will prioritize a "better" target even if the plane is wrong.

For example, here the plugin ends up going to the top of the castle as it can walk onto the exact x,y coordinate picked which is blocked on the chosen plane.

![java_YSpxfrYfZG](https://github.com/user-attachments/assets/73a145a9-0f7b-41c2-8439-858ca512a4af)

**Comment by Skretzo** [comment]
This was added in version 1.15.2 and will be live in the client after review in a few days or 1 to 2 weeks.

I actually remember explicitly disregarding the z-plane, but I can no longer remember why I did that. It could have been that many ladders and staircases were missing, which would create even worse paths to unreachable targets cross-plane. This is a much smaller problem now as most ladders and staircases have been added, so I have decided to change cross-plane distance from 0 to almost infinity.
